#!/bin/sh
mipsel-unknown-elf-g++ -D__PSXSDK__ -fsigned-char -msoft-float -mno-gpopt -fno-builtin -G0 -I/usr/local/psxsdk/include -T /usr/local/psxsdk/mipsel-unknown-elf/lib/ldscripts/playstation.x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-use-cxa-atexit $*
