include ../Makefile.cfg

all: 
	$(MAKE_COMMAND) -C mandel
	$(MAKE_COMMAND) -C memview
	$(MAKE_COMMAND) -C psxmod
	$(MAKE_COMMAND) -C psxpaint
	$(MAKE_COMMAND) -C psxsnake
	$(MAKE_COMMAND) -C puzzle
	$(MAKE_COMMAND) -C rottest
	$(MAKE_COMMAND) -C psxs3m
	$(MAKE_COMMAND) -C gtecube
	
clean: 
	$(MAKE_COMMAND) -C mandel clean
	$(MAKE_COMMAND) -C memview clean
	$(MAKE_COMMAND) -C psxmod clean
	$(MAKE_COMMAND) -C psxpaint clean
	$(MAKE_COMMAND) -C psxsnake clean
	$(MAKE_COMMAND) -C puzzle clean
	$(MAKE_COMMAND) -C rottest clean
	$(MAKE_COMMAND) -C psxs3m clean
	$(MAKE_COMMAND) -C gtecube clean

distclean: clean
